export const avatarKategorije = {
  base: ['1.svg'],
  ears: ['Attached.svg', 'Detached.svg'],
  earrings: ['Hoop.svg', 'Stud.svg'],
  eyebrows: ['Down.svg', 'Eyelashes Down.svg', 'Eyelashes Up.svg', 'Up.svg'],
  eyes: ['Eyes.svg', 'Eyeshadow.svg', 'Round.svg', 'Smiling.svg'],
  facialHair: ['Beard.svg', 'Scruff.svg'],
  glasses: ['Round.svg', 'Square.svg'],
  hair: ['Danny Phantom.svg', 'Doug Funny.svg', 'Fonze.svg', 'Full.svg', 'Mr Clean.svg', 'Mr T.svg', 'Pixie.svg', 'Turban.svg'],
  mouth: ['Frown.svg', 'Laughing.svg', 'Nervous.svg', 'Pucker.svg', 'Sad.svg', 'Smile.svg', 'Smirk.svg', 'Surprised.svg'],
  nose: ['Curve.svg', 'Pointed.svg', 'Round.svg'],
  shirt: ['Collared.svg', 'Crew.svg', 'Open.svg'],
};

export const pozadina = 'Background.svg';
export const ocekivaniBrojKomponenti = 39;
export const ignoriraniTopLevelExporti = [
  'Background-1.svg',
  'Base.svg',
  'Color.svg',
  'Ears.svg',
  'Ear Ring.svg',
  'Ellipse 100.svg',
  'Ellipse 101.svg',
  'Ellipse 102.svg',
  'Ellipse 103.svg',
  'Ellipse 104.svg',
  'Ellipse 105.svg',
  'Ellipse 106.svg',
  'Ellipse 107.svg',
  'Ellipse 108.svg',
  'Ellipse 96.svg',
  'Ellipse 97.svg',
  'Ellipse 98.svg',
  'Ellipse 99.svg',
  'Eyebrows.svg',
  'Eyes.svg',
  'Facial Hair.svg',
  'Glasses.svg',
  'Library.svg',
  'Mouth.svg',
  'Nose.svg',
  'Shirt.svg',
  'Tops.svg',
];
